# -*- coding: utf-8 -*-
"""confirmed cases ARIMA & pmARIMA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzNxxZaYMHTXhJcNXK_maVG83LoNt2MR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA

df =  pd.read_excel("FCG1.xlsx")

df['Date']=pd.to_datetime(df['Date'])

result = df.groupby('Date')['Confirmed'].sum().reset_index()

result.set_index("Date",inplace=True)

result

result.plot()

order=(5,1,5) #(p,d,q)order
model=ARIMA(df['Confirmed'],order=order)
results=model.fit()

#Forecast future sales values
forecast_steps=30
forecast=results.forecast(steps=forecast_steps)



plt.figure(figsize=(10,6))
plt.plot(result['Confirmed'])
# plt.plot(df['Confirmed'],label='Actual Sales')
plt.plot(pd.date_range(start=result.index[-1],periods=forecast_steps,freq='D'),forecast,
        label='ARIMA Forecast',color='red')
plt.xlabel("Month")
plt.ylabel("Sales")
plt.title("ARIMA Forecast for Sales")
plt.legend()
plt.show()

"""# New Code

"""

pip install pmdarima

import pmdarima as pm
from pmdarima.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

y = result
train, test = train_test_split(y, train_size=150)

model = pm.auto_arima(train, seasonal=False, m=12)

forecasts = model.predict(test.shape[0])

x = np.arange(y.shape[0])
plt.plot(x[:150], train, c='blue')
plt.plot(x[150:], forecasts, c='green')
plt.show()

