# -*- coding: utf-8 -*-
"""seasonality test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xKb0Xc5J3yh5AoA1qwsoFZQ21mI3fAe1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA
import numpy as np

pip install pmdarima

import pmdarima as pm
from pmdarima.model_selection import train_test_split

df =  pd.read_excel("FCG1.xlsx")

df['Date']=pd.to_datetime(df['Date'])

result = df.groupby('Date')['Confirmed'].sum().reset_index()

#result.set_index("Date",inplace=True)

y = result
train, test = train_test_split(y, train_size=150)

import plotly.express as px
from statsmodels.tsa.stattools import adfuller

train

x=train["Date"]
y=train["Confirmed"]

plt.plot(x,y)

result.set_index("Date",inplace=True)

"""ADF test"""

from statsmodels.tsa.stattools import adfuller


def adf_test(series):
    """Using an ADF test to determine if a series is stationary"""
    test_results = adfuller(series)
    print('ADF Statistic: ', test_results[0])
    print('Critical Values:')
    for thres, adf_stat in test_results[4].items():
        print('\t%s: %.2f' % (thres, adf_stat))

#data["Passenger_Season_Diff"][12:]
y=pd.DataFrame(y)
adf_test(y.iloc[:,0])

